app/forms/dropdown_form.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField


class DropdownForm(FlaskForm):
      sorting_options = SelectField('', choices=['Sort by', 'Newest first', 'Oldest first', 'Most popular'])
      # submit=SubmitField('Submit')

app/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log in')

app/forms/post_form.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from flask_pagedown.fields import PageDownField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = PageDownField('Title (Markdown enabled)', validators=[DataRequired(), Length(min=0, max=250)])
    post = PageDownField('Content (Markdown enabled)', render_kw={'class': 'form-control', 'rows': 10}, validators=[DataRequired(), Length(min=0, max=2500)])
    submit = SubmitField('Save')

app/forms/register_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo, ValidationError, Email
from app.models.models import User


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email is not None:
            raise ValidationError('Please use a different email address.')

app/forms/update_profile_form.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, FileField, ValidationError
from wtforms.validators import DataRequired, Length
from app.models.models import User


class UpdateProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    info = TextAreaField('About me', validators=[Length(min=0, max=2500)])
    # profile_image = FileField('Profile image', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')


    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

app/routes/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_user, logout_user, login_required
from app.forms.login_form import LoginForm
from app.forms.register_form import RegisterForm
from app.forms.update_profile_form import UpdateProfileForm
from app.forms.post_form import PostForm
from app.forms.update_post_form import UpdatePostForm
from app.forms.delete_post_form import DeletePostForm
from app.forms.comment_form import CommentForm
from app.forms.dropdown_form import DropdownForm
from app.models import db
from app.models.models import User, Post, Comment
from flask import Blueprint

blueprint = Blueprint('main', __name__)


@blueprint.route('/', methods=["GET", "POST"])
@blueprint.route('/home', methods=["GET", "POST"])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    per_page = 2
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=per_page, error_out=False)
    form = DropdownForm()
    return render_template("index.html", posts=posts, form=form)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first_or_404()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password')
            return redirect(url_for('main.login'))
        login_user(user)
        return redirect(url_for('main.index'))
    return render_template('login_form.html', form=form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@blueprint.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = User()
        new_user.username = form.username.data
        new_user.email = form.email.data
        new_user.isAdmin = False
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Congratulations, you have registered!')
        return redirect(url_for('main.login'))
    return render_template('register_form.html', form=form)


@blueprint.route('/user/<username>', methods=["GET", "POST"])
@login_required
def user(username):
        user = User.query.filter_by(username=username).first_or_404()
        print(user.id)
        form = PostForm()
        page = request.args.get('page', 1, type=int)
        per_page = 2
        if form.validate_on_submit():
            new_post = Post()
            new_post.title=form.title.data
            new_post.body=form.post.data
            new_post.user_id=user.id
            db.session.add(new_post)
            db.session.commit()
            flash('Your post has been saved.')
            return redirect(url_for('main.user', username=username))
        user.profile_image = user.get_avatar(128)
        posts = Post.query.filter_by(user_id=user.id).order_by(Post.timestamp.desc())
        posts_count = Post.query.filter_by(user_id=user.id).order_by(Post.timestamp.desc()).count()
        print(posts_count)
        if posts_count > 0:
            paginated_posts = posts.paginate(page=page, per_page=per_page, error_out=False)
            return render_template('profile.html', user=user, form=form, posts=paginated_posts)
        else:
            return render_template('profile.html', user=user, form=form)


@blueprint.route('/update_profile', methods=["GET", "POST"])
@login_required
def update_profile():
    form = UpdateProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.info = form.info.data
        # current_user.profile_image = form.profile_image.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.user', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.info.data = current_user.info
        # form.profile_image.data = current_user.profile_image
    return render_template('update_profile_form.html',
                           form=form)


@blueprint.route('/update_post/<id>', methods=["GET", "POST"])
@login_required
def update_post(id):
    post = Post.query.filter_by(id=id).first_or_404()
    user = User.query.filter_by(id=post.user_id).first_or_404()

    update_post_form = UpdatePostForm()
    delete_post_form = DeletePostForm()

    if update_post_form.validate_on_submit():
        updated_post = Post(body=update_post_form.post.data, user_id=user.id, title=update_post_form.title.data)
        post.title = updated_post.title
        post.body = updated_post.body
        db.session.commit()
        flash('Your post has been changed.')
        return redirect(url_for('main.user', username=user.username))
    elif request.method == 'GET':
        update_post_form.post.data = post.body
        update_post_form.title.data = post.title
    return render_template('manage_post.html',
                           update_post_form=update_post_form, delete_post_form=delete_post_form, id=id)


@blueprint.route('/delete_post/<id>', methods=["GET", "POST"])
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first_or_404()
    user = User.query.filter_by(id=post.user_id).first_or_404()

    update_post_form = UpdatePostForm()
    delete_post_form = DeletePostForm()

    if delete_post_form.validate_on_submit():
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted.')
        return redirect(url_for('main.user', username=user.username))
    elif request.method == 'GET':
        update_post_form.post.data = post.body
        update_post_form.title.data = post.title
    return render_template('manage_post.html', 
                           update_post_form=update_post_form, delete_post_form=delete_post_form, id=id)


@blueprint.route('/post/<id>', methods=["GET", "POST"])
@login_required
def post(id):
    post = Post.query.filter_by(id=id).first_or_404()
    post_author = User.query.filter_by(id=post.user_id).first_or_404()
    if not post.views and post_author != current_user:
        post.views = 1
    elif post.views and post_author != current_user:
        post.views += 1
    db.session.commit()
    form = CommentForm()
    if form.validate_on_submit():
            new_comment = Comment()
            new_comment.content = form.content.data
            new_comment.post_id = id
            new_comment.user_id = current_user.id
            db.session.add(new_comment)
            db.session.commit()
            flash('Your comment has been added.')
            return redirect(url_for('main.post', id=id))

    comments = Comment.query.filter_by(post_id=id).order_by(Comment.timestamp.desc()).all()
    return render_template('post.html',
                           post=post,
                           title='Add comment',
                           form=form, post_author=post_author, comments=comments)


@blueprint.route('/sort/<sort_by>', methods=["GET", "POST"])
@login_required
def sort(sort_by):
    form=DropdownForm()
    page = request.args.get('page', 1, type=int)
    per_page = 2
    if sort_by == 'newest':
        posts = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=per_page, error_out=False)
        return render_template("index.html", posts=posts, form=form, sort_by=sort_by)
    elif sort_by == 'oldest':
        posts = Post.query.order_by(Post.timestamp.asc()).paginate(page=page, per_page=per_page, error_out=False)
        return render_template("index.html",  posts=posts, form=form, sort_by=sort_by)
    elif sort_by == 'popular':
        posts = Post.query.order_by(Post.views.desc()).paginate(page=page, per_page=per_page, error_out=False)
        return render_template("index.html", posts=posts, form=form, sort_by=sort_by)
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template("index.html", posts=posts, form=form)

    

    

app/templates/base.html
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {{ pagedown.html_head() }}
        <title>My blog</title>
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
            integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link rel="stylesheet" href="../static/style.css" />
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{{url_for('main.index')}}">My Blog</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav float-right text-right mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
                    </li>
                     <li class="nav-item">
                        <a
                            class="nav-link"
                            href="{{url_for('main.user', username=current_user.username)}}"
                            >Add post</a
                        >
                    </li>
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            href="{{url_for('main.user', username=current_user.username)}}"
                            >Profile</a
                        >
                    </li></ul>
                    {% if current_user.is_authenticated%}
                     <ul class="navbar-nav float-right text-right ms-auto">
                        <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.logout')}}"
                            >Logout</a>

                    </li>
                    </ul>

                    {% endif %}
                </ul>
            </div>
        </nav>

        {% with messages = get_flashed_messages() %} {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul>
                {% for message in messages %}
                <li>{{ message[0:-1] }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %} {% endwith %} {% block content %}{% endblock %}
        <script
            src="{{url_for('static', filename='index.js')}}"
            type="text/javascript"
        ></script>
        <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

app/templates/dropdown_form.html
{% extends "base.html" %}{% import "bootstrap/wtf.html" as wtf %} {% block
content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10 col-xs-10">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endfor %} {% endif %} {% endblock %}

app/templates/index.html
{% extends "base.html" %}{% import "bootstrap/wtf.html" as wtf %} {% block
content %} {% if current_user.isAdmin %}

<div class="admin-view-link"><a href="/admin">Admin view</a></div>
<div class="extra">
    <h1 class="greeting">Hi, {{current_user.username }}!</h1>
</div>
{% else %}
<h1 class="greeting">Hi, {{current_user.username }}!</h1>
{% endif %}




{% if posts %}
<!--<div class="container">-->
<!--    <div class="row mt-2">-->
<!--        <div class="form-group">-->

<!--            <label class="d-inline-block" for="sorting_options">Sort by:</label>-->

<!--            <select name="sorting_options" class="form-control form-control-sm d-inline-block" style="width: auto;" id="sorting_options" >-->
<!--               <option value="Newest first"><a class="dropdown-item" href="{{url_for('main.sort', sort_by='newest')}}"-->
<!--            >Newest first</a-->
<!--               ></option>-->

<!--        <option value="Oldest first"><a class="dropdown-item" href="{{url_for('main.sort', sort_by='oldest')}}"-->
<!--            >Oldest first</a-->
<!--        ></option>-->
<!--        <option value="Most popular"><a class="dropdown-item" href="{{url_for('main.sort', sort_by='popular')}}"-->
<!--            >Most popular</a-->
<!--        ></option>-->
<!--            </select>-->

<!--        </div>-->
<!--    </div>-->
<!--</div>-->




<div class="dropdown" id="sorting_options">
    <button
        class="btn btn-secondary dropdown-toggle"
        type="button"
        id="dropdownMenuButton"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
    >
        Sort by
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{{url_for('main.sort', sort_by='newest')}}"
            >Newest first</a
        >
        <a class="dropdown-item" href="{{url_for('main.sort', sort_by='oldest')}}"
            >Oldest first</a
        >
        <a class="dropdown-item" href="{{url_for('main.sort', sort_by='popular')}}"
            >Most popular</a
        >
    </div>
</div>
{% for post in posts %}
<div class="posts">
    <ul>
        <a href="{{url_for('main.post', id=post.id)}}" class="post-link">
            <li class="post">
                <div class="avatar-comment">
                    <div>
                        {% if post.title_html %}
                        {{post.title_html | safe}}
                        {% else %}
                        <p class="comment-title">{{ post.title}}</p>
                        {% endif %}
                        {% if post.body_html %}
                        {{(post.body_html | safe)[0:250]}}...>>
                        {% else %}
                        {{post.body[0:250]}}...>>
                        {% endif %}
                    </div>
                </div>
                <div class="comments-date">
                    <div class="comments-views">
                        {% if not post.views%}
                        <p>👁️‍🗨️ 0</p>
                        {% else %}
                        <p>👁️‍🗨️ {{post.views}}</p>
                        {% endif %}
                        <p>💬 {{post.get_comments_length()}}</p>
                    </div>
                    <p>Posted on</p>
                    <p>{{post.timestamp.strftime('%d/%m/%Y')}}</p>
                    by {{post.user.username}}

                    <a href="{{url_for('main.user', username=post.user.username)}}">
                        <img src="{{ post.user.get_avatar(64) }}"
                    /></a>
                </div></li
        ></a>
    </ul>
</div>
{% endfor %}
{% if not sort_by %}
<div class="arrows">
    {% if posts.has_prev %}
    <a href="{{ url_for('main.index', page=posts.prev_num) }}"><i class="fa-solid fa-angles-left"></i>Previous</a>
    {% endif %}
    {% if posts.has_next %}
    <a href="{{ url_for('main.index', page=posts.next_num) }}">Next<i class="fa-solid fa-angles-right"></i>️</a>
    {% endif %}
</div>
{% else %}
<div class="arrows">
    {% if posts.has_prev %}
    <a href="{{ url_for('main.sort', sort_by=sort_by, page=posts.prev_num) }}"><i class="fa-solid fa-angles-left"></i>Previous</a>
    {% endif %}
    {% if posts.has_next %}
    <a href="{{ url_for('main.sort',sort_by=sort_by, page=posts.next_num) }}">Next<i class="fa-solid fa-angles-right"></i>️</a>
    {% endif %}
</div>
{%endif%}
{% else %}
<h4 class="greeting">No posts yet</h4>
<h4 class="greeting">Be the first to create a post</h4>
{% endif %}{% endblock %}

app/templates/login_form.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %} {% block
content %}
<div class="login-title">
    <h1>Log in</h1>
    <h5>
        New User? <a href="{{ url_for('main.register') }}">Click to Register!</a>
    </h5>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-8 col-xs-10">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/manage_post.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}{% block
content %}
<div class="back-button">
<h1 class="greeting">Update or delete your post</h1>
<a
        class="btn btn-default back-button"
        href="{{ url_for('main.post', id=id) }}"
        >Back to post</a>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-sm-10 col-xs-10">
            {{ wtf.quick_form(update_post_form) }}
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-sm-10 col-xs-10">
            <form
                    action="{{url_for('main.delete_post', id=id)}}"
                    method="post"
                    novalidate
            >
                {{ delete_post_form.hidden_tag() }}
                {{ delete_post_form.submit() }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}{% import "bootstrap/wtf.html" as wtf %} {% block
content %}


{% if post.title_html %}
    <div class="greeting">{{ post.title_html | safe}}</div>
{% else %}
    <div class="greeting">{{ post.title}}</div>
{% endif %}
<div class="date">
     <a href="{{url_for('main.user', username=post.user.username)}}"><img src="{{ post.user.get_avatar(20) }}"
    /> {{post_author.username}}'s
    post</a>
    <p>posted on {{post.timestamp.strftime('%d/%m/%Y')}}</p>
</div>
<div class="post-text">

    {% if post.body_html%}
        {{post.body_html | safe}}
    {% else %}
        {{post.body}}
    {% endif%}
{% if post_author == current_user%}
<a
        class="btn btn-default edit-button"
        href="{{ url_for('main.update_post', id=post.id) }}"
        >Edit</a
    >
{% endif%}

</div>
</br>
<hr>
</br>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10 col-xs-10">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>

</br>
<hr>
</br>

{% if comments %}
<h2 class="greeting">Comments</h2>
{% for comment in comments %}
<div class="posts">
    <ul>
        <li class="post">
            <div class="avatar-comment">
                <img src="{{ comment.user.get_avatar(20) }}" />
                {{ comment }}
            </div>
            <div class="comments-date">
                <p>Posted on</p>
                <p>{{comment.timestamp.strftime('%d/%m/%Y')}}</p>
                <p>by {{ comment.user.username }}</p>
            </div>
        </li>
    </ul>
</div>
{% endfor %} {% endif %} {% endblock %}

app/templates/profile.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}{% block
content %}
<div class="avatar-username">
    <div class="avatar-username">
        <img src="{{ user.profile_image }}" width="128" height="128" />
        <div>
            <h1>{{ user.username }}</h1>
            {% if user.info %}
            <h2>{{user.info}}</h2>
            {% endif %}
        </div>
    </div>
    {% if current_user == user%}
    <div class="update-profile-link">
        <a href="{{ url_for('main.update_profile') }}">Update profile</a>
    </div>
    {% endif %}
</div>
<hr />
{% if current_user == user%}
<h3 class="greeting">Create a new post</h3>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-10 col-xs-10">
            {{ wtf.quick_form(form)}}
        </div>
    </div>
</div>

<hr />
{% endif %}
{% if posts %}
<h2 class="greeting">{{user.username}}'s posts</h2>
{% for post in posts%}
<div class="posts">
    <ul>
        <a href="{{url_for('main.post', id=post.id)}}" class="post-link">
            <li class="post">
                <div class="avatar-comment">
                    <div>
                        {% if post.title_html %}
                        {{post.title_html | safe}}
                        {% else %}
                        <p class="comment-title">{{ post.title}}</p>
                        {% endif %}
                        {% if post.body_html %}
                        {{(post.body_html | safe)[0:250]}}...>>
                        {% else %}
                        {{post.body[0:250]}}...>>
                        {% endif %}
                    </div>
                </div>
                <div class="comments-date">
                    <div class="comments-views">
                        {% if not post.views%}
                        <p>👁️‍🗨️ 0</p>
                        {% else %}
                        <p>👁️‍🗨️ {{post.views}}</p>
                        {% endif %}
                        <p>💬 {{post.get_comments_length()}}</p>
                    </div>
                    <p>Posted on</p>
                    <p>{{post.timestamp.strftime('%d/%m/%Y')}}</p>
                </div>
            </li></a
        >
    </ul>
</div>
{% endfor%}
<div class="arrows">
    {% if posts.has_prev %}
    <a href="{{ url_for('main.user', username=user.username, page=posts.prev_num) }}"><i class="fa-solid fa-angles-left"></i>Previous</a>
    {% endif %}
    {% if posts.has_next %}
    <a href="{{ url_for('main.user',username=user.username, page=posts.next_num) }}">Next<i class="fa-solid fa-angles-right"></i>️</a>
    {% endif %}
</div>

{% endif %} {% endblock %}

app/templates/register_form.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %} {% block
content %}
<div class="register-title">
    <h1>Register</h1>
    <h5>
        Already a User? <a href="{{ url_for('main.login') }}">Click to Login!</a>
    </h5>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-8 col-xs-10">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/update_profile_form.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %} {% block
content %}
<h1 class="greeting">Update Profile</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10 col-xs-10">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}